### ISSUE TITLE
使用老的sbf报错， Cannot read properties of undefined (reading 'width')，有可能超过最大长度

### ISSUE THREAD

**Issue by DaNaoFu11** [SilenceLeo/snowb-bmf#103]
Failed to load resource: the server responded with a status of 429 ()
main.2fc0d24f.js:1 TypeError: Cannot read properties of undefined (reading 'width')
    at main.2fc0d24f.js:1:1176191
    at Array.map (<anonymous>)
    at e.get (main.2fc0d24f.js:1:1176163)
    at Zd (main.2fc0d24f.js:1:919944)
    at e.computeValue_ (main.2fc0d24f.js:1:918202)
    at e.trackAndCompute (main.2fc0d24f.js:1:918046)
    at e.get (main.2fc0d24f.js:1:917280)
    at e.getObservablePropValue_ (main.2fc0d24f.js:1:946550)
    at e.get (main.2fc0d24f.js:1:951336)
    at e.value (main.2fc0d24f.js:1:1176572)
    at Ed (main.2fc0d24f.js:1:913646)
    at e.pack (main.2fc0d24f.js:1:913188)
    at new e (main.2fc0d24f.js:1:1175917)
    at e.value (main.2fc0d24f.js:1:1181033)
    at Ed (main.2fc0d24f.js:1:913646)
    at addProject (main.2fc0d24f.js:1:913188)
    at main.2fc0d24f.js:1:1789502
2main.2fc0d24f.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'width')
    at main.2fc0d24f.js:1:1176191
    at Array.map (<anonymous>)
    at e.get (main.2fc0d24f.js:1:1176163)
    at Zd (main.2fc0d24f.js:1:919944)
    at e.computeValue_ (main.2fc0d24f.js:1:918202)
    at e.trackAndCompute (main.2fc0d24f.js:1:918046)
    at e.get (main.2fc0d24f.js:1:917280)
    at e.getObservablePropValue_ (main.2fc0d24f.js:1:946550)
    at e.get (main.2fc0d24f.js:1:951336)
    at e.value (main.2fc0d24f.js:1:1176572)
    at Ed (main.2fc0d24f.js:1:913646)
    at pack (main.2fc0d24f.js:1:913188)
snowb.org/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
6main.2fc0d24f.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'width')
    at main.2fc0d24f.js:1:1176191
    at Array.map (<anonymous>)
    at e.get (main.2fc0d24f.js:1:1176163)
    at Zd (main.2fc0d24f.js:1:919944)
    at e.computeValue_ (main.2fc0d24f.js:1:918202)
    at e.trackAndCompute (main.2fc0d24f.js:1:918046)
    at e.get (main.2fc0d24f.js:1:917280)
    at e.getObservablePropValue_ (main.2fc0d24f.js:1:946550)
    at e.get (main.2fc0d24f.js:1:951336)
    at e.value (main.2fc0d24f.js:1:1176572)
    at Ed (main.2fc0d24f.js:1:913646)
    at pack (main.2fc0d24f.js:1:913188)

**Comment by DaNaoFu11** [comment]
6728个字，感觉是超过最大数量了或者计算超时了？打出图片尺寸是3300*3300

**Comment by DaNaoFu11** [comment]
嗯 在附件里


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SilenceLeo/snowb-bmf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 晚上8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SilenceLeo/snowb-bmf] 使用老的sbf报错， Cannot read properties of undefined (reading 'width')，有可能超过最大长度 (Issue #103)





 
能把sdf文件发出来吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

1common32.sbf (4.74M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=77653565860ed1cd11477c734432571d4d110152550b505018515751571f0605535018540400071f560703540102550704010755623f6503560a58080d5c56001b165703620f&t=exs_ftn_download&code=5e5eb2e2

**Comment by SilenceLeo** [comment]
旧版本在保存时没有兼容emoji，导入后还需要从新编辑一下字符。

**Comment by DaNaoFu11** [comment]
现在网站上部署的版本已经修好了吗？因为我刚才直接使用还是会报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SilenceLeo/snowb-bmf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SilenceLeo/snowb-bmf] 使用老的sbf报错， Cannot read properties of undefined (reading 'width')，有可能超过最大长度 (Issue #103)





 
旧版本在保存时没有兼容emoji，导入后还需要从新编辑一下字符。
